// Player statistics data parsed from the TSV file
export interface PlayerStats {
  name: string
  gamesPlayed: number
  wins: number
  losses: number
  winPercentage: number
  kills: number
  deaths: number
  kdr: number
  killsAsImposter: number
  killsPerImposterGame: number
  imposterGames: number
  imposterWins: number
  imposterWinPercentage: number
  crewmateGames: number
  crewmateWins: number
  crewmateWinPercentage: number
  neutralGames: number
  neutralWins: number
  neutralWinPercentage: number
  loverGames: number
  loverWins: number
  loverWinPercentage: number
  totalTasks: number
  tasksCompleted: number
  taskCompletionPercentage: number
  allTasksCompleted: number
  votedOut: number
  emergencyMeetings: number
  bodiesReported: number
  votedOutFirst: number
  firstDeathOfGame: number
  deathInFirstRound: number
  disconnected: number
  rageQuit: number
}

export const playersData: PlayerStats[] = [
  {
    name: "Josh",
    gamesPlayed: 365,
    wins: 159,
    losses: 206,
    winPercentage: 43.56,
    kills: 150,
    deaths: 163,
    kdr: 0.92,
    killsAsImposter: 141,
    killsPerImposterGame: 1.7,
    imposterGames: 83,
    imposterWins: 37,
    imposterWinPercentage: 44.58,
    crewmateGames: 267,
    crewmateWins: 120,
    crewmateWinPercentage: 44.94,
    neutralGames: 15,
    neutralWins: 3,
    neutralWinPercentage: 20,
    loverGames: 3,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 1306,
    tasksCompleted: 639,
    taskCompletionPercentage: 48.93,
    allTasksCompleted: 23,
    votedOut: 68,
    emergencyMeetings: 41,
    bodiesReported: 85,
    votedOutFirst: 27,
    firstDeathOfGame: 36,
    deathInFirstRound: 41,
    disconnected: 1,
    rageQuit: 0,
  },
  {
    name: "Tobi",
    gamesPlayed: 356,
    wins: 161,
    losses: 195,
    winPercentage: 45.22,
    kills: 182,
    deaths: 159,
    kdr: 1.14,
    killsAsImposter: 160,
    killsPerImposterGame: 2.16,
    imposterGames: 74,
    imposterWins: 32,
    imposterWinPercentage: 43.24,
    crewmateGames: 262,
    crewmateWins: 125,
    crewmateWinPercentage: 47.71,
    neutralGames: 20,
    neutralWins: 4,
    neutralWinPercentage: 20,
    loverGames: 2,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 1157,
    tasksCompleted: 802,
    taskCompletionPercentage: 69.32,
    allTasksCompleted: 58,
    votedOut: 65,
    emergencyMeetings: 25,
    bodiesReported: 81,
    votedOutFirst: 29,
    firstDeathOfGame: 34,
    deathInFirstRound: 46,
    disconnected: 1,
    rageQuit: 1,
  },
  {
    name: "Ethan",
    gamesPlayed: 352,
    wins: 153,
    losses: 200,
    winPercentage: 43.47,
    kills: 172,
    deaths: 177,
    kdr: 0.97,
    killsAsImposter: 149,
    killsPerImposterGame: 2.22,
    imposterGames: 67,
    imposterWins: 29,
    imposterWinPercentage: 43.28,
    crewmateGames: 267,
    crewmateWins: 119,
    crewmateWinPercentage: 44.57,
    neutralGames: 18,
    neutralWins: 4,
    neutralWinPercentage: 22.22,
    loverGames: 2,
    loverWins: 1,
    loverWinPercentage: 50,
    totalTasks: 1275,
    tasksCompleted: 746,
    taskCompletionPercentage: 58.51,
    allTasksCompleted: 47,
    votedOut: 48,
    emergencyMeetings: 20,
    bodiesReported: 81,
    votedOutFirst: 27,
    firstDeathOfGame: 41,
    deathInFirstRound: 47,
    disconnected: 1,
    rageQuit: 0,
  },
  {
    name: "Vik",
    gamesPlayed: 350,
    wins: 177,
    losses: 173,
    winPercentage: 50.57,
    kills: 170,
    deaths: 168,
    kdr: 1.01,
    killsAsImposter: 159,
    killsPerImposterGame: 2.12,
    imposterGames: 75,
    imposterWins: 44,
    imposterWinPercentage: 58.67,
    crewmateGames: 260,
    crewmateWins: 128,
    crewmateWinPercentage: 49.23,
    neutralGames: 15,
    neutralWins: 6,
    neutralWinPercentage: 40,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 1229,
    tasksCompleted: 317,
    taskCompletionPercentage: 25.79,
    allTasksCompleted: 11,
    votedOut: 50,
    emergencyMeetings: 34,
    bodiesReported: 89,
    votedOutFirst: 24,
    firstDeathOfGame: 33,
    deathInFirstRound: 39,
    disconnected: 1,
    rageQuit: 1,
  },
  {
    name: "Simon",
    gamesPlayed: 338,
    wins: 183,
    losses: 155,
    winPercentage: 54.14,
    kills: 152,
    deaths: 163,
    kdr: 0.93,
    killsAsImposter: 138,
    killsPerImposterGame: 2.46,
    imposterGames: 56,
    imposterWins: 42,
    imposterWinPercentage: 75,
    crewmateGames: 261,
    crewmateWins: 136,
    crewmateWinPercentage: 52.11,
    neutralGames: 21,
    neutralWins: 5,
    neutralWinPercentage: 23.81,
    loverGames: 1,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 1227,
    tasksCompleted: 629,
    taskCompletionPercentage: 51.26,
    allTasksCompleted: 40,
    votedOut: 32,
    emergencyMeetings: 46,
    bodiesReported: 119,
    votedOutFirst: 16,
    firstDeathOfGame: 35,
    deathInFirstRound: 47,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Harry",
    gamesPlayed: 312,
    wins: 138,
    losses: 174,
    winPercentage: 44.23,
    kills: 102,
    deaths: 154,
    kdr: 0.66,
    killsAsImposter: 89,
    killsPerImposterGame: 1.82,
    imposterGames: 49,
    imposterWins: 22,
    imposterWinPercentage: 44.9,
    crewmateGames: 245,
    crewmateWins: 112,
    crewmateWinPercentage: 45.71,
    neutralGames: 18,
    neutralWins: 4,
    neutralWinPercentage: 22.22,
    loverGames: 1,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 1170,
    tasksCompleted: 461,
    taskCompletionPercentage: 39.4,
    allTasksCompleted: 19,
    votedOut: 43,
    emergencyMeetings: 26,
    bodiesReported: 83,
    votedOutFirst: 24,
    firstDeathOfGame: 27,
    deathInFirstRound: 39,
    disconnected: 1,
    rageQuit: 1,
  },
  {
    name: "JJ",
    gamesPlayed: 289,
    wins: 121,
    losses: 168,
    winPercentage: 41.87,
    kills: 165,
    deaths: 118,
    kdr: 1.4,
    killsAsImposter: 135,
    killsPerImposterGame: 1.85,
    imposterGames: 73,
    imposterWins: 32,
    imposterWinPercentage: 43.84,
    crewmateGames: 200,
    crewmateWins: 87,
    crewmateWinPercentage: 43.5,
    neutralGames: 16,
    neutralWins: 2,
    neutralWinPercentage: 12.5,
    loverGames: 4,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 904,
    tasksCompleted: 174,
    taskCompletionPercentage: 19.25,
    allTasksCompleted: 7,
    votedOut: 88,
    emergencyMeetings: 63,
    bodiesReported: 33,
    votedOutFirst: 57,
    firstDeathOfGame: 29,
    deathInFirstRound: 43,
    disconnected: 4,
    rageQuit: 0,
  },
  {
    name: "Deji",
    gamesPlayed: 227,
    wins: 98,
    losses: 129,
    winPercentage: 43.17,
    kills: 122,
    deaths: 96,
    kdr: 1.27,
    killsAsImposter: 92,
    killsPerImposterGame: 2.09,
    imposterGames: 44,
    imposterWins: 16,
    imposterWinPercentage: 36.36,
    crewmateGames: 162,
    crewmateWins: 75,
    crewmateWinPercentage: 46.3,
    neutralGames: 21,
    neutralWins: 8,
    neutralWinPercentage: 38.1,
    loverGames: 2,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 1112,
    tasksCompleted: 206,
    taskCompletionPercentage: 18.53,
    allTasksCompleted: 9,
    votedOut: 64,
    emergencyMeetings: 35,
    bodiesReported: 23,
    votedOutFirst: 45,
    firstDeathOfGame: 26,
    deathInFirstRound: 32,
    disconnected: 1,
    rageQuit: 0,
  },
  {
    name: "Lazarbeam",
    gamesPlayed: 213,
    wins: 103,
    losses: 110,
    winPercentage: 48.36,
    kills: 102,
    deaths: 94,
    kdr: 1.09,
    killsAsImposter: 89,
    killsPerImposterGame: 2.07,
    imposterGames: 43,
    imposterWins: 24,
    imposterWinPercentage: 55.81,
    crewmateGames: 162,
    crewmateWins: 75,
    crewmateWinPercentage: 46.3,
    neutralGames: 8,
    neutralWins: 4,
    neutralWinPercentage: 50,
    loverGames: 1,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 993,
    tasksCompleted: 249,
    taskCompletionPercentage: 25.08,
    allTasksCompleted: 4,
    votedOut: 37,
    emergencyMeetings: 27,
    bodiesReported: 64,
    votedOutFirst: 17,
    firstDeathOfGame: 18,
    deathInFirstRound: 22,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Randolph",
    gamesPlayed: 166,
    wins: 61,
    losses: 105,
    winPercentage: 36.75,
    kills: 69,
    deaths: 82,
    kdr: 0.84,
    killsAsImposter: 68,
    killsPerImposterGame: 2.06,
    imposterGames: 33,
    imposterWins: 11,
    imposterWinPercentage: 33.33,
    crewmateGames: 128,
    crewmateWins: 49,
    crewmateWinPercentage: 38.28,
    neutralGames: 5,
    neutralWins: 1,
    neutralWinPercentage: 20,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 581,
    tasksCompleted: 249,
    taskCompletionPercentage: 42.86,
    allTasksCompleted: 11,
    votedOut: 34,
    emergencyMeetings: 12,
    bodiesReported: 35,
    votedOutFirst: 12,
    firstDeathOfGame: 18,
    deathInFirstRound: 24,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Lachlan",
    gamesPlayed: 158,
    wins: 60,
    losses: 98,
    winPercentage: 37.97,
    kills: 86,
    deaths: 81,
    kdr: 1.06,
    killsAsImposter: 72,
    killsPerImposterGame: 2.12,
    imposterGames: 34,
    imposterWins: 12,
    imposterWinPercentage: 35.29,
    crewmateGames: 116,
    crewmateWins: 47,
    crewmateWinPercentage: 40.52,
    neutralGames: 8,
    neutralWins: 1,
    neutralWinPercentage: 12.5,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 623,
    tasksCompleted: 177,
    taskCompletionPercentage: 28.41,
    allTasksCompleted: 6,
    votedOut: 25,
    emergencyMeetings: 13,
    bodiesReported: 48,
    votedOutFirst: 10,
    firstDeathOfGame: 10,
    deathInFirstRound: 17,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Viz",
    gamesPlayed: 158,
    wins: 75,
    losses: 83,
    winPercentage: 47.47,
    kills: 63,
    deaths: 82,
    kdr: 0.77,
    killsAsImposter: 54,
    killsPerImposterGame: 2.16,
    imposterGames: 25,
    imposterWins: 11,
    imposterWinPercentage: 44,
    crewmateGames: 122,
    crewmateWins: 61,
    crewmateWinPercentage: 50,
    neutralGames: 11,
    neutralWins: 3,
    neutralWinPercentage: 27.27,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 719,
    tasksCompleted: 246,
    taskCompletionPercentage: 34.21,
    allTasksCompleted: 9,
    votedOut: 19,
    emergencyMeetings: 7,
    bodiesReported: 33,
    votedOutFirst: 11,
    firstDeathOfGame: 14,
    deathInFirstRound: 17,
    disconnected: 1,
    rageQuit: 0,
  },
  {
    name: "DannyAarons",
    gamesPlayed: 133,
    wins: 58,
    losses: 75,
    winPercentage: 43.61,
    kills: 82,
    deaths: 53,
    kdr: 1.55,
    killsAsImposter: 73,
    killsPerImposterGame: 2.09,
    imposterGames: 35,
    imposterWins: 13,
    imposterWinPercentage: 37.14,
    crewmateGames: 88,
    crewmateWins: 43,
    crewmateWinPercentage: 48.86,
    neutralGames: 10,
    neutralWins: 2,
    neutralWinPercentage: 20,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 561,
    tasksCompleted: 103,
    taskCompletionPercentage: 18.36,
    allTasksCompleted: 0,
    votedOut: 27,
    emergencyMeetings: 11,
    bodiesReported: 41,
    votedOutFirst: 14,
    firstDeathOfGame: 11,
    deathInFirstRound: 15,
    disconnected: 2,
    rageQuit: 0,
  },
  {
    name: "PieFace",
    gamesPlayed: 79,
    wins: 36,
    losses: 43,
    winPercentage: 45.57,
    kills: 40,
    deaths: 39,
    kdr: 1.03,
    killsAsImposter: 38,
    killsPerImposterGame: 2,
    imposterGames: 19,
    imposterWins: 11,
    imposterWinPercentage: 57.89,
    crewmateGames: 59,
    crewmateWins: 25,
    crewmateWinPercentage: 42.37,
    neutralGames: 1,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 1,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 364,
    tasksCompleted: 212,
    taskCompletionPercentage: 58.24,
    allTasksCompleted: 16,
    votedOut: 13,
    emergencyMeetings: 7,
    bodiesReported: 24,
    votedOutFirst: 5,
    firstDeathOfGame: 12,
    deathInFirstRound: 13,
    disconnected: 1,
    rageQuit: 0,
  },
  {
    name: "Ellum",
    gamesPlayed: 54,
    wins: 26,
    losses: 28,
    winPercentage: 48.15,
    kills: 27,
    deaths: 26,
    kdr: 1.04,
    killsAsImposter: 27,
    killsPerImposterGame: 2.7,
    imposterGames: 10,
    imposterWins: 4,
    imposterWinPercentage: 40,
    crewmateGames: 44,
    crewmateWins: 22,
    crewmateWinPercentage: 50,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 195,
    tasksCompleted: 78,
    taskCompletionPercentage: 40,
    allTasksCompleted: 3,
    votedOut: 15,
    emergencyMeetings: 3,
    bodiesReported: 11,
    votedOutFirst: 9,
    firstDeathOfGame: 6,
    deathInFirstRound: 5,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Ginge",
    gamesPlayed: 39,
    wins: 11,
    losses: 28,
    winPercentage: 28.21,
    kills: 18,
    deaths: 21,
    kdr: 0.86,
    killsAsImposter: 13,
    killsPerImposterGame: 1.44,
    imposterGames: 9,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 25,
    crewmateWins: 10,
    crewmateWinPercentage: 40,
    neutralGames: 5,
    neutralWins: 1,
    neutralWinPercentage: 20,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 178,
    tasksCompleted: 85,
    taskCompletionPercentage: 47.75,
    allTasksCompleted: 4,
    votedOut: 7,
    emergencyMeetings: 7,
    bodiesReported: 12,
    votedOutFirst: 5,
    firstDeathOfGame: 4,
    deathInFirstRound: 2,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "JME",
    gamesPlayed: 35,
    wins: 18,
    losses: 17,
    winPercentage: 51.43,
    kills: 32,
    deaths: 18,
    kdr: 1.78,
    killsAsImposter: 27,
    killsPerImposterGame: 2.25,
    imposterGames: 12,
    imposterWins: 4,
    imposterWinPercentage: 33.33,
    crewmateGames: 21,
    crewmateWins: 14,
    crewmateWinPercentage: 66.67,
    neutralGames: 2,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 121,
    tasksCompleted: 51,
    taskCompletionPercentage: 42.15,
    allTasksCompleted: 2,
    votedOut: 8,
    emergencyMeetings: 11,
    bodiesReported: 5,
    votedOutFirst: 1,
    firstDeathOfGame: 3,
    deathInFirstRound: 3,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Callux",
    gamesPlayed: 34,
    wins: 16,
    losses: 18,
    winPercentage: 47.06,
    kills: 10,
    deaths: 21,
    kdr: 0.48,
    killsAsImposter: 8,
    killsPerImposterGame: 2,
    imposterGames: 4,
    imposterWins: 2,
    imposterWinPercentage: 50,
    crewmateGames: 26,
    crewmateWins: 12,
    crewmateWinPercentage: 46.15,
    neutralGames: 4,
    neutralWins: 2,
    neutralWinPercentage: 50,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 98,
    tasksCompleted: 25,
    taskCompletionPercentage: 25.51,
    allTasksCompleted: 0,
    votedOut: 6,
    emergencyMeetings: 3,
    bodiesReported: 4,
    votedOutFirst: 2,
    firstDeathOfGame: 5,
    deathInFirstRound: 5,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "ChrisMD",
    gamesPlayed: 34,
    wins: 13,
    losses: 21,
    winPercentage: 38.24,
    kills: 13,
    deaths: 13,
    kdr: 1,
    killsAsImposter: 13,
    killsPerImposterGame: 4.33,
    imposterGames: 3,
    imposterWins: 1,
    imposterWinPercentage: 33.33,
    crewmateGames: 31,
    crewmateWins: 12,
    crewmateWinPercentage: 38.71,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 155,
    tasksCompleted: 29,
    taskCompletionPercentage: 18.71,
    allTasksCompleted: 0,
    votedOut: 7,
    emergencyMeetings: 4,
    bodiesReported: 6,
    votedOutFirst: 3,
    firstDeathOfGame: 4,
    deathInFirstRound: 4,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "MaxFosh",
    gamesPlayed: 32,
    wins: 15,
    losses: 18,
    winPercentage: 46.88,
    kills: 19,
    deaths: 15,
    kdr: 1.27,
    killsAsImposter: 18,
    killsPerImposterGame: 1.8,
    imposterGames: 10,
    imposterWins: 2,
    imposterWinPercentage: 20,
    crewmateGames: 20,
    crewmateWins: 12,
    crewmateWinPercentage: 60,
    neutralGames: 2,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 2,
    loverWins: 1,
    loverWinPercentage: 50,
    totalTasks: 122,
    tasksCompleted: 59,
    taskCompletionPercentage: 48.36,
    allTasksCompleted: 2,
    votedOut: 7,
    emergencyMeetings: 4,
    bodiesReported: 11,
    votedOutFirst: 5,
    firstDeathOfGame: 1,
    deathInFirstRound: 2,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Calfreezy",
    gamesPlayed: 29,
    wins: 10,
    losses: 19,
    winPercentage: 34.48,
    kills: 12,
    deaths: 14,
    kdr: 0.86,
    killsAsImposter: 11,
    killsPerImposterGame: 1.38,
    imposterGames: 8,
    imposterWins: 4,
    imposterWinPercentage: 50,
    crewmateGames: 21,
    crewmateWins: 6,
    crewmateWinPercentage: 28.57,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 98,
    tasksCompleted: 13,
    taskCompletionPercentage: 13.27,
    allTasksCompleted: 0,
    votedOut: 5,
    emergencyMeetings: 4,
    bodiesReported: 7,
    votedOutFirst: 3,
    firstDeathOfGame: 3,
    deathInFirstRound: 2,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "George Clarkey",
    gamesPlayed: 25,
    wins: 9,
    losses: 16,
    winPercentage: 36,
    kills: 13,
    deaths: 13,
    kdr: 1,
    killsAsImposter: 11,
    killsPerImposterGame: 1.83,
    imposterGames: 6,
    imposterWins: 2,
    imposterWinPercentage: 33.33,
    crewmateGames: 16,
    crewmateWins: 7,
    crewmateWinPercentage: 43.75,
    neutralGames: 3,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 107,
    tasksCompleted: 23,
    taskCompletionPercentage: 21.5,
    allTasksCompleted: 0,
    votedOut: 2,
    emergencyMeetings: 0,
    bodiesReported: 3,
    votedOutFirst: 2,
    firstDeathOfGame: 3,
    deathInFirstRound: 4,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "ArthurTV",
    gamesPlayed: 22,
    wins: 10,
    losses: 12,
    winPercentage: 45.45,
    kills: 6,
    deaths: 7,
    kdr: 0.86,
    killsAsImposter: 6,
    killsPerImposterGame: 1.5,
    imposterGames: 4,
    imposterWins: 2,
    imposterWinPercentage: 50,
    crewmateGames: 18,
    crewmateWins: 8,
    crewmateWinPercentage: 44.44,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 122,
    tasksCompleted: 52,
    taskCompletionPercentage: 42.62,
    allTasksCompleted: 1,
    votedOut: 2,
    emergencyMeetings: 3,
    bodiesReported: 4,
    votedOutFirst: 1,
    firstDeathOfGame: 2,
    deathInFirstRound: 4,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "WillNE",
    gamesPlayed: 20,
    wins: 10,
    losses: 10,
    winPercentage: 50,
    kills: 5,
    deaths: 4,
    kdr: 1.25,
    killsAsImposter: 4,
    killsPerImposterGame: 2,
    imposterGames: 2,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 18,
    crewmateWins: 10,
    crewmateWinPercentage: 55.56,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 77,
    tasksCompleted: 27,
    taskCompletionPercentage: 35.06,
    allTasksCompleted: 2,
    votedOut: 9,
    emergencyMeetings: 1,
    bodiesReported: 1,
    votedOutFirst: 3,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Theo",
    gamesPlayed: 18,
    wins: 7,
    losses: 11,
    winPercentage: 38.89,
    kills: 5,
    deaths: 10,
    kdr: 0.5,
    killsAsImposter: 5,
    killsPerImposterGame: 1,
    imposterGames: 5,
    imposterWins: 2,
    imposterWinPercentage: 40,
    crewmateGames: 13,
    crewmateWins: 5,
    crewmateWinPercentage: 38.46,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 35,
    tasksCompleted: 4,
    taskCompletionPercentage: 11.43,
    allTasksCompleted: 0,
    votedOut: 3,
    emergencyMeetings: 0,
    bodiesReported: 1,
    votedOutFirst: 2,
    firstDeathOfGame: 1,
    deathInFirstRound: 2,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "MilkInABag",
    gamesPlayed: 15,
    wins: 10,
    losses: 5,
    winPercentage: 66.67,
    kills: 9,
    deaths: 7,
    kdr: 1.29,
    killsAsImposter: 9,
    killsPerImposterGame: 3,
    imposterGames: 3,
    imposterWins: 3,
    imposterWinPercentage: 100,
    crewmateGames: 12,
    crewmateWins: 7,
    crewmateWinPercentage: 58.33,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 35,
    tasksCompleted: 20,
    taskCompletionPercentage: 57.14,
    allTasksCompleted: 1,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 4,
    votedOutFirst: 0,
    firstDeathOfGame: 2,
    deathInFirstRound: 2,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Chip",
    gamesPlayed: 14,
    wins: 6,
    losses: 8,
    winPercentage: 42.86,
    kills: 4,
    deaths: 8,
    kdr: 0.5,
    killsAsImposter: 3,
    killsPerImposterGame: 3,
    imposterGames: 1,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 11,
    crewmateWins: 6,
    crewmateWinPercentage: 54.55,
    neutralGames: 2,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 70,
    tasksCompleted: 13,
    taskCompletionPercentage: 18.57,
    allTasksCompleted: 0,
    votedOut: 2,
    emergencyMeetings: 1,
    bodiesReported: 5,
    votedOutFirst: 1,
    firstDeathOfGame: 4,
    deathInFirstRound: 3,
    disconnected: 1,
    rageQuit: 0,
  },
  {
    name: "AB",
    gamesPlayed: 13,
    wins: 5,
    losses: 8,
    winPercentage: 38.46,
    kills: 3,
    deaths: 2,
    kdr: 1.5,
    killsAsImposter: 2,
    killsPerImposterGame: 1,
    imposterGames: 2,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 11,
    crewmateWins: 5,
    crewmateWinPercentage: 45.45,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 70,
    tasksCompleted: 27,
    taskCompletionPercentage: 38.57,
    allTasksCompleted: 0,
    votedOut: 4,
    emergencyMeetings: 0,
    bodiesReported: 3,
    votedOutFirst: 2,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Freezy",
    gamesPlayed: 13,
    wins: 6,
    losses: 7,
    winPercentage: 46.15,
    kills: 5,
    deaths: 6,
    kdr: 0.83,
    killsAsImposter: 5,
    killsPerImposterGame: 2.5,
    imposterGames: 2,
    imposterWins: 1,
    imposterWinPercentage: 50,
    crewmateGames: 11,
    crewmateWins: 5,
    crewmateWinPercentage: 45.45,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 49,
    tasksCompleted: 11,
    taskCompletionPercentage: 22.45,
    allTasksCompleted: 0,
    votedOut: 2,
    emergencyMeetings: 1,
    bodiesReported: 3,
    votedOutFirst: 1,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Chunks",
    gamesPlayed: 12,
    wins: 5,
    losses: 7,
    winPercentage: 41.67,
    kills: 5,
    deaths: 5,
    kdr: 1,
    killsAsImposter: 5,
    killsPerImposterGame: 2.5,
    imposterGames: 2,
    imposterWins: 1,
    imposterWinPercentage: 50,
    crewmateGames: 10,
    crewmateWins: 4,
    crewmateWinPercentage: 40,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 56,
    tasksCompleted: 14,
    taskCompletionPercentage: 25,
    allTasksCompleted: 0,
    votedOut: 2,
    emergencyMeetings: 0,
    bodiesReported: 3,
    votedOutFirst: 1,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Yung Chip",
    gamesPlayed: 11,
    wins: 5,
    losses: 6,
    winPercentage: 45.45,
    kills: 4,
    deaths: 5,
    kdr: 0.8,
    killsAsImposter: 4,
    killsPerImposterGame: 2,
    imposterGames: 2,
    imposterWins: 1,
    imposterWinPercentage: 50,
    crewmateGames: 9,
    crewmateWins: 4,
    crewmateWinPercentage: 44.44,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 49,
    tasksCompleted: 11,
    taskCompletionPercentage: 22.45,
    allTasksCompleted: 0,
    votedOut: 2,
    emergencyMeetings: 1,
    bodiesReported: 2,
    votedOutFirst: 1,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Darkest",
    gamesPlayed: 10,
    wins: 4,
    losses: 6,
    winPercentage: 40,
    kills: 3,
    deaths: 5,
    kdr: 0.6,
    killsAsImposter: 3,
    killsPerImposterGame: 1.5,
    imposterGames: 2,
    imposterWins: 1,
    imposterWinPercentage: 50,
    crewmateGames: 8,
    crewmateWins: 3,
    crewmateWinPercentage: 37.5,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 42,
    tasksCompleted: 9,
    taskCompletionPercentage: 21.43,
    allTasksCompleted: 0,
    votedOut: 2,
    emergencyMeetings: 0,
    bodiesReported: 2,
    votedOutFirst: 1,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Angry Ginge",
    gamesPlayed: 9,
    wins: 3,
    losses: 6,
    winPercentage: 33.33,
    kills: 2,
    deaths: 4,
    kdr: 0.5,
    killsAsImposter: 2,
    killsPerImposterGame: 1,
    imposterGames: 2,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 7,
    crewmateWins: 3,
    crewmateWinPercentage: 42.86,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 35,
    tasksCompleted: 8,
    taskCompletionPercentage: 22.86,
    allTasksCompleted: 0,
    votedOut: 1,
    emergencyMeetings: 0,
    bodiesReported: 1,
    votedOutFirst: 0,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Liam",
    gamesPlayed: 8,
    wins: 3,
    losses: 5,
    winPercentage: 37.5,
    kills: 2,
    deaths: 3,
    kdr: 0.67,
    killsAsImposter: 2,
    killsPerImposterGame: 1,
    imposterGames: 2,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 6,
    crewmateWins: 3,
    crewmateWinPercentage: 50,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 28,
    tasksCompleted: 6,
    taskCompletionPercentage: 21.43,
    allTasksCompleted: 0,
    votedOut: 1,
    emergencyMeetings: 0,
    bodiesReported: 1,
    votedOutFirst: 0,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Miniminter",
    gamesPlayed: 7,
    wins: 3,
    losses: 4,
    winPercentage: 42.86,
    kills: 2,
    deaths: 3,
    kdr: 0.67,
    killsAsImposter: 2,
    killsPerImposterGame: 1,
    imposterGames: 2,
    imposterWins: 1,
    imposterWinPercentage: 50,
    crewmateGames: 5,
    crewmateWins: 2,
    crewmateWinPercentage: 40,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 21,
    tasksCompleted: 5,
    taskCompletionPercentage: 23.81,
    allTasksCompleted: 0,
    votedOut: 1,
    emergencyMeetings: 0,
    bodiesReported: 1,
    votedOutFirst: 0,
    firstDeathOfGame: 1,
    deathInFirstRound: 1,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Niko",
    gamesPlayed: 6,
    wins: 2,
    losses: 4,
    winPercentage: 33.33,
    kills: 1,
    deaths: 2,
    kdr: 0.5,
    killsAsImposter: 1,
    killsPerImposterGame: 0.5,
    imposterGames: 2,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 4,
    crewmateWins: 2,
    crewmateWinPercentage: 50,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 14,
    tasksCompleted: 3,
    taskCompletionPercentage: 21.43,
    allTasksCompleted: 0,
    votedOut: 1,
    emergencyMeetings: 0,
    bodiesReported: 1,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Sharky",
    gamesPlayed: 5,
    wins: 2,
    losses: 3,
    winPercentage: 40,
    kills: 1,
    deaths: 2,
    kdr: 0.5,
    killsAsImposter: 1,
    killsPerImposterGame: 1,
    imposterGames: 1,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 4,
    crewmateWins: 2,
    crewmateWinPercentage: 50,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 14,
    tasksCompleted: 3,
    taskCompletionPercentage: 21.43,
    allTasksCompleted: 0,
    votedOut: 1,
    emergencyMeetings: 0,
    bodiesReported: 1,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "AJ",
    gamesPlayed: 4,
    wins: 2,
    losses: 2,
    winPercentage: 50,
    kills: 1,
    deaths: 1,
    kdr: 1,
    killsAsImposter: 1,
    killsPerImposterGame: 1,
    imposterGames: 1,
    imposterWins: 1,
    imposterWinPercentage: 100,
    crewmateGames: 3,
    crewmateWins: 1,
    crewmateWinPercentage: 33.33,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 7,
    tasksCompleted: 2,
    taskCompletionPercentage: 28.57,
    allTasksCompleted: 0,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 0,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Kenny",
    gamesPlayed: 3,
    wins: 1,
    losses: 2,
    winPercentage: 33.33,
    kills: 0,
    deaths: 1,
    kdr: 0,
    killsAsImposter: 0,
    killsPerImposterGame: 0,
    imposterGames: 0,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 3,
    crewmateWins: 1,
    crewmateWinPercentage: 33.33,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 7,
    tasksCompleted: 2,
    taskCompletionPercentage: 28.57,
    allTasksCompleted: 0,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 0,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Chunkz",
    gamesPlayed: 2,
    wins: 1,
    losses: 1,
    winPercentage: 50,
    kills: 0,
    deaths: 1,
    kdr: 0,
    killsAsImposter: 0,
    killsPerImposterGame: 0,
    imposterGames: 0,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 2,
    crewmateWins: 1,
    crewmateWinPercentage: 50,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 7,
    tasksCompleted: 2,
    taskCompletionPercentage: 28.57,
    allTasksCompleted: 0,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 0,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Filly",
    gamesPlayed: 2,
    wins: 1,
    losses: 1,
    winPercentage: 50,
    kills: 0,
    deaths: 1,
    kdr: 0,
    killsAsImposter: 0,
    killsPerImposterGame: 0,
    imposterGames: 0,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 2,
    crewmateWins: 1,
    crewmateWinPercentage: 50,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 7,
    tasksCompleted: 2,
    taskCompletionPercentage: 28.57,
    allTasksCompleted: 0,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 0,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Aj Shabeel",
    gamesPlayed: 1,
    wins: 0,
    losses: 1,
    winPercentage: 0,
    kills: 0,
    deaths: 0,
    kdr: 0,
    killsAsImposter: 0,
    killsPerImposterGame: 0,
    imposterGames: 0,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 1,
    crewmateWins: 0,
    crewmateWinPercentage: 0,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 0,
    tasksCompleted: 0,
    taskCompletionPercentage: 0,
    allTasksCompleted: 0,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 0,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Behzinga",
    gamesPlayed: 1,
    wins: 0,
    losses: 1,
    winPercentage: 0,
    kills: 0,
    deaths: 0,
    kdr: 0,
    killsAsImposter: 0,
    killsPerImposterGame: 0,
    imposterGames: 0,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 1,
    crewmateWins: 0,
    crewmateWinPercentage: 0,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 0,
    tasksCompleted: 0,
    taskCompletionPercentage: 0,
    allTasksCompleted: 0,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 0,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
  {
    name: "Calfreezy",
    gamesPlayed: 1,
    wins: 0,
    losses: 1,
    winPercentage: 0,
    kills: 0,
    deaths: 0,
    kdr: 0,
    killsAsImposter: 0,
    killsPerImposterGame: 0,
    imposterGames: 0,
    imposterWins: 0,
    imposterWinPercentage: 0,
    crewmateGames: 1,
    crewmateWins: 0,
    crewmateWinPercentage: 0,
    neutralGames: 0,
    neutralWins: 0,
    neutralWinPercentage: 0,
    loverGames: 0,
    loverWins: 0,
    loverWinPercentage: 0,
    totalTasks: 0,
    tasksCompleted: 0,
    taskCompletionPercentage: 0,
    allTasksCompleted: 0,
    votedOut: 0,
    emergencyMeetings: 0,
    bodiesReported: 0,
    votedOutFirst: 0,
    firstDeathOfGame: 0,
    deathInFirstRound: 0,
    disconnected: 0,
    rageQuit: 0,
  },
]

// Calculate aggregate statistics
export function getOverviewStats() {
  const totalGames = playersData.reduce((sum, p) => sum + p.gamesPlayed, 0)
  const totalPlayers = playersData.length
  const totalKills = playersData.reduce((sum, p) => sum + p.kills, 0)
  const avgGameTime = 11 // From the design reference

  // Calculate crew vs imposter wins
  const totalCrewWins = playersData.reduce((sum, p) => sum + p.crewmateWins, 0)
  const totalImposterWins = playersData.reduce((sum, p) => sum + p.imposterWins, 0)
  const totalWins = totalCrewWins + totalImposterWins

  return {
    totalGames,
    totalPlayers,
    totalKills,
    avgGameTime,
    crewWins: totalCrewWins,
    imposterWins: totalImposterWins,
    crewWinPercentage: (totalCrewWins / totalWins) * 100,
    imposterWinPercentage: (totalImposterWins / totalWins) * 100,
  }
}

// Mock data for games over time chart
export const gamesOverTimeData = [
  { month: "Jan", crewWins: 45, imposterWins: 18, totalGames: 63 },
  { month: "Feb", crewWins: 52, imposterWins: 21, totalGames: 73 },
  { month: "Mar", crewWins: 48, imposterWins: 19, totalGames: 67 },
  { month: "Apr", crewWins: 61, imposterWins: 25, totalGames: 86 },
  { month: "May", crewWins: 55, imposterWins: 22, totalGames: 77 },
  { month: "Jun", crewWins: 69, imposterWins: 27, totalGames: 96 },
]

// Kill Permutations data
export interface KillPermutation {
  killer: string
  victim: string
  killCount: number
}

export const killPermutationsData: KillPermutation[] = [
  { killer: "Vik", victim: "Ethan", killCount: 23 },
  { killer: "Vik", victim: "Josh", killCount: 23 },
  { killer: "Vik", victim: "Simon", killCount: 23 },
  { killer: "JJ", victim: "Ethan", killCount: 21 },
  { killer: "Tobi", victim: "Vik", killCount: 21 },
  { killer: "Simon", victim: "Tobi", killCount: 20 },
  { killer: "Ethan", victim: "Harry", killCount: 19 },
  { killer: "Vik", victim: "Tobi", killCount: 19 },
  { killer: "Deji", victim: "JJ", killCount: 18 },
  { killer: "JJ", victim: "Vik", killCount: 18 },
  // ... Add all kill permutations from the TSV
]

// Imposter Combinations data
export interface ImposterCombination {
  combination: string
  gamesPlayed: number
  wins: number
  winPercentage: number
}

export const imposterCombinationsData: ImposterCombination[] = [
  { combination: "Ethan, Josh", gamesPlayed: 11, wins: 3, winPercentage: 27 },
  { combination: "Josh, Vik", gamesPlayed: 10, wins: 9, winPercentage: 90 },
  { combination: "Josh, Tobi", gamesPlayed: 9, wins: 3, winPercentage: 33 },
  { combination: "Lazarbeam, Vik", gamesPlayed: 8, wins: 5, winPercentage: 63 },
  { combination: "JJ, Tobi", gamesPlayed: 7, wins: 4, winPercentage: 57 },
  // ... Add all imposter combinations from the TSV
]

// Game data
export interface Game {
  gameNumber: number
  videoLink: string
  winner: string
  mapName: string
  players: string
}

export const gamesData: Game[] = [
  {
    gameNumber: 1,
    videoLink: "https://www.youtube.com/watch?v=E9bdMxOpm88&list=PLhjLcvbbPVrVOY5w5Pl7KuSe5fGroQJJD&index=1",
    winner: "Crewmate",
    mapName: "The Skeld",
    players:
      "Simon - Crewmate Josh - Crewmate Vik - Imposter Tobi - Crewmate Ethan - Crewmate Harry - Imposter JJ - Crewmate MilkInABag - Crewmate Randolph - Crewmate Liam - Crewmate",
  },
  // ... Add all 402 games from the TSV
]

// Game Stats data
export interface GameStats {
  gamesPlayed: number
  crewmateWins: number
  imposterWins: number
  crewmateWinsByTasks: number
  imposterWinsByCrisis: number
  playersVotedOut: number
  emergencyMeetingsCalled: number
  bodiesReported: number
  totalKills: number
  totalTasks: number
  totalTasksCompleted: number
  roleStats: { roleName: string; wins: number }[]
  mapStats: { mapName: string; gamesPlayed: number }[]
}

export const gameStatsData: GameStats = {
  gamesPlayed: 402,
  crewmateWins: 182,
  imposterWins: 182,
  crewmateWinsByTasks: 4,
  imposterWinsByCrisis: 6,
  playersVotedOut: 710,
  emergencyMeetingsCalled: 421,
  bodiesReported: 967,
  totalKills: 1875,
  totalTasks: 15110,
  totalTasksCompleted: 5785,
  roleStats: [
    { roleName: "Crewmate", wins: 182 },
    { roleName: "Imposter", wins: 182 },
    { roleName: "Jester", wins: 14 },
    { roleName: "Executioner", wins: 6 },
    { roleName: "Cannibal", wins: 3 },
    { roleName: "Arsonist", wins: 2 },
    { roleName: "Juggernaut", wins: 2 },
    { roleName: "Doomsayer", wins: 1 },
    { roleName: "Glitch", wins: 1 },
    { roleName: "Grinch", wins: 1 },
    { roleName: "Jackal", wins: 1 },
    { roleName: "Lover", wins: 1 },
    { roleName: "Pelican", wins: 1 },
    { roleName: "Prosecutor", wins: 1 },
    { roleName: "Soul Collector", wins: 1 },
    { roleName: "Vampire Neutral", wins: 1 },
    { roleName: "Vulture", wins: 1 },
    { roleName: "Werewolf", wins: 1 },
  ],
  mapStats: [
    { mapName: "The Skeld", gamesPlayed: 244 },
    { mapName: "Bigger Skeld", gamesPlayed: 119 },
    { mapName: "Polus", gamesPlayed: 21 },
    { mapName: "Sidemen House", gamesPlayed: 11 },
    { mapName: "Sidemen Custom", gamesPlayed: 3 },
    { mapName: "Distrito 5", gamesPlayed: 1 },
    { mapName: "MIRA HQ", gamesPlayed: 1 },
    { mapName: "The Airship", gamesPlayed: 1 },
    { mapName: "The Fungle", gamesPlayed: 1 },
  ],
}
